version: "3.9"

services:
  # caddy:
  #   image: caddy:latest
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   env_file:
  #     - .env
  #   volumes:
  #     - ./Caddyfile:/etc/caddy/Caddyfile

  web:
    build: .
    depends_on:
      - database
    restart: always
    ports:
      - "80:3000"
    volumes:
      - ./data:/app/data

  database:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: minitwit
      POSTGRES_PASSWORD: minitwit
      POSTGRES_DB: minitwit
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus/
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3001:3000"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD}
  node-exporter:
    image: prom/node-exporter
    ports:
      - "9100:9100"
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - "--path.procfs=/host/proc"
      - "--path.sysfs=/host/sys"
      - "--path.rootfs=/rootfs"

volumes:
  prometheus_data:
  grafana_data:
  db_data:
